# House Price Prediction Project

## 1. Problem Definition:
* Goal: Predic the sales price for each house

## 2. Feature Selection:
- Choose features to train ML Model
- Need to use `Feature Engineering` to identify needed

## 3. Spliting the datasets:
- `data` : dataset
- `X` : data[features]
- `y` : data[SalePrice]

## 4. Training Machibe Learning Model

In [76]:
# Import libraries
import pandas as pd
import numpy as np

In [77]:
data = pd.read_csv("./Data/train.csv",index_col="Id")

In [78]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [79]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

## 2. Feature Selection:

In [80]:
features = ["LotArea","YearBuilt","TotalBsmtSF","1stFlrSF","2ndFlrSF",
            "FullBath","HalfBath","BedroomAbvGr","KitchenAbvGr","TotRmsAbvGrd"]

## 3. Spliting dataset into X and y:

In [81]:
X = data[features]
y = data["SalePrice"]

In [82]:
X.head()

LotArea  YearBuilt  TotalBsmtSF  1stFlrSF  2ndFlrSF  FullBath  HalfBath  \
Id                                                                            
1      8450       2003          856       856       854         2         1   
2      9600       1976         1262      1262         0         2         0   
3     11250       2001          920       920       866         2         1   
4      9550       1915          756       961       756         1         0   
5     14260       2000         1145      1145      1053         2         1   

    BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  
Id                                            
1              3             1             8  
2              3             1             6  
3              3             1             6  
4              3             1             7  
5              4             1             9

In [83]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

### X,y to X_train , y_train, X_valid, y_valid 

In [84]:
from sklearn.model_selection import train_test_split

X = X.values
y = y.values

X_train,X_valid,y_train,y_valid =  train_test_split(X,y,train_size=0.8,test_size=0.2,random_state=0)

In [85]:
X_train.shape

(1168, 10)

In [86]:
X_valid.shape

(292, 10)

In [87]:
X.shape

(1460, 10)

## 4.Training Machine Learning Model
* Link Introduction DecisionTreeRegressor: https://www.kaggle.com/code/dansbecker/how-models-work

In [88]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=1)

In [89]:
# fit training data into model
dt_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=1)

In [90]:
y_preds=dt_model.predict(X_valid)

In [91]:
y_preds[:5]

array([180000., 109000., 109500., 207500.,  75000.])

In [92]:
pd.DataFrame({'y': y_valid,'y_preds':y_preds})

y   y_preds
0    200624  180000.0
1    133000  109000.0
2    110000  109500.0
3    192000  207500.0
4     88000   75000.0
..      ...       ...
287  324000  285000.0
288  555000  501837.0
289  136000  214500.0
290   82500   92000.0
291  101000   78000.0

[292 rows x 2 columns]

In [93]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

rf_model = RandomForestRegressor(random_state=1)

In [94]:
rf_model.fit(X_train,y_train)

RandomForestRegressor(random_state=1)

In [95]:
preds = rf_model.predict(X_valid)

In [96]:
preds[:10]

array([268500.81      , 136697.02      , 113337.        , 195125.79      ,
        91464.33333333,  91673.5       , 249439.45      , 131781.72      ,
       631203.33      , 174304.14      ])

### Predict with a new input

In [113]:
pd.DataFrame(features)

0
0       LotArea
1     YearBuilt
2   TotalBsmtSF
3      1stFlrSF
4      2ndFlrSF
5      FullBath
6      HalfBath
7  BedroomAbvGr
8  KitchenAbvGr
9  TotRmsAbvGrd

In [105]:
val = [11111,2023,2023,2000,1000,2,0,4,1,10]

In [106]:
rf_model.predict([val])

array([407637.5])