# Suppost Vector Machine Using Python Sklearn
---


![](https://raw.githubusercontent.com/codebasics/py/master/ML/10_svm/iris_petal_sepal.png)

In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt

In [3]:
iris = datasets.load_iris()

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [16]:
df[df.target == 0].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [17]:
df[df.target == 1].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
50       1  
51       1  
52       1  
53       1  
54       1

In [18]:
df[df.target == 2].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2.5   
101                5.8               2.7                5.1               1.9   
102                7.1               3.0                5.9               2.1   
103                6.3               2.9                5.6               1.8   
104                6.5               3.0                5.8               2.2   

     target  
100       2  
101       2  
102       2  
103       2  
104       2

In [19]:
df['flower_name'] = df.target.apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target flower_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

In [20]:
df[50:55]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target flower_name  
50       1  versicolor  
51       1  versicolor  
52       1  versicolor  
53       1  versicolor  
54       1  versicolor

In [21]:
df[100:105]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2.5   
101                5.8               2.7                5.1               1.9   
102                7.1               3.0                5.9               2.1   
103                6.3               2.9                5.6               1.8   
104                6.5               3.0                5.8               2.2   

     target flower_name  
100       2   virginica  
101       2   virginica  
102       2   virginica  
103       2   virginica  
104       2   virginica

In [22]:
X = df.drop(['target', 'flower_name'], axis = 'columns')
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [23]:
y = df['target']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size= 0.2, random_state= 124)

In [25]:
X_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
131                7.9               3.8                6.4               2.0
143                6.8               3.2                5.9               2.3
75                 6.6               3.0                4.4               1.4
14                 5.8               4.0                1.2               0.2
29                 4.7               3.2                1.6               0.2

In [26]:
y_train.head()

131    2
143    2
75     1
14     0
29     0
Name: target, dtype: int64

In [27]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)

SVC()

In [29]:
pre = model.predict(X_test)
pre[:5]

array([1, 0, 1, 2, 2])

In [30]:
y_test[:5]

56     1
16     0
87     1
134    2
136    2
Name: target, dtype: int64

In [31]:
model.score(X_test, y_test)

0.9333333333333333

# Ture Parameters

# 1. Regularrization (C)

In [36]:
model_C = SVC(C = 1.0)
model_C.fit(X_train, y_train)
model_C.score(X_test,y_test)

0.9333333333333333

In [38]:
model_C = SVC(C = 10.0)
model_C.fit(X_train, y_train)
model_C.score(X_test,y_test)

0.9

# 2. Gamma 

In [39]:
model_gamma = SVC(gamma= 10.0)
model_gamma.fit(X_train, y_train)
model_gamma.score(X_test, y_test)

0.9

# 3. Kernel

In [40]:
model_kernel_linear = SVC(kernel = 'linear')
model_kernel_linear.fit(X_train, y_train)
model_kernel_linear.score(X_test, y_test)

0.9

In [41]:
model_kernel_rbf = SVC(kernel = 'rbf')
model_kernel_rbf.fit(X_train, y_train)
model_kernel_rbf.score(X_test, y_test)

0.9333333333333333

In [42]:
model_kernel_s = SVC(kernel = 'sigmoid')
model_kernel_s.fit(X_train, y_train)
model_kernel_s.score(X_test, y_test)

0.3

In [43]:
model_kernel_poly = SVC(kernel = 'poly')
model_kernel_poly.fit(X_train, y_train)
model_kernel_poly.score(X_test, y_test)

0.9

# Execire

Train SVM classifier using sklearn digits dataset (i.e from sklearn.datasets import load_digits) and then,

1. Measure accuracy of your model using different kernel such as `rbf` and `linear`
2. Ture your model further using `regularization` and `gamma` parameter and try to come up with hight `accuracy score`
3. Use 80% of samples as training data size

In [44]:
from sklearn.datasets import load_digits

digits = load_digits()

In [46]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [47]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [50]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.2, random_state = 124)

In [52]:
X_train[0]

array([ 0.,  0.,  2., 15.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16.,  4.,
        0.,  0.,  0.,  0.,  3., 16.,  7.,  0.,  0.,  0.,  0.,  0.,  4.,
       16.,  6.,  4.,  1.,  0.,  0.,  0.,  6., 16., 16., 14., 16.,  3.,
        0.,  0.,  2., 14.,  9.,  0., 11.,  9.,  0.,  0.,  0., 10., 14.,
        8., 15.,  5.,  0.,  0.,  0.,  3., 13., 16.,  8.,  0.,  0.])

In [53]:
y_train[0]

6

In [59]:
model_kerne = SVC(kernel = 'rbf')
model_kerne.fit(X_train, y_train)
model_kerne.score(X_test,y_test)

0.9833333333333333

In [60]:
model_kernel = SVC(kernel = 'linear')
model_kerne.fit(X_train, y_train)
model_kerne.score(X_test,y_test)

0.9833333333333333

In [62]:
model_C = SVC(C = 1.0)
model_C.fit(X_train, y_train)
model_C.score(X_test,y_test)

0.9833333333333333

In [63]:
model_C = SVC(C = 10)
model_C.fit(X_train, y_train)
model_C.score(X_test,y_test)

0.9861111111111112

In [64]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.9833333333333333

In [66]:
model_gamma = SVC(gamma = 1.0)
model_gamma.fit(X_train, y_train)
model_gamma.score(X_test,y_test)

0.07777777777777778